[cage] fix PARROT_CANNOT_RETURN_NULL, add HASATTRIBUTE_FORMAT_* variants
* PARROT_CANNOT_RETURN_NULL was empty, thus never detected when used on
  wrong declarations. Implement it now,
  e.g. ./include/parrot/packfile.h:353:9:
  error: returns_nonnull attribute on a function not returning a pointer
* HASATTRIBUTE_FORMAT has multiple variants. try gun_printf, ms_printf
  or printf. Not yet used.
* bring together the definition and it's non-defined counterpart. they are
  currently seperated.  if you add one, you should not forget to add the
  other part.

See GH #1163.