[tools] include <sys/sysctl.h> for pbc_to_exe on FreeBSD
While compiling pbc_to_exe I got errors like
pbc_to_exe.c:1301:22: error: use of undeclared identifier 'CTL_KERN'
(probably after commit 3c00e7e19969971383e50fb58d31ace46a702828

Including sys/sysctl.h on FreeBSD solves that problem.

Signed-off-by: Reini Urban <rurban@cpanel.net>