[cage] Correcting undeclared interp errors
This patch fixes

    error: ‘interp’ undeclared (first use in this function)

compiler errors.  It seems that using PARROT_INTERP instead of SHIM_INTERP
is the correct thing to do here (PARROT_INTERP is what is documented in the
docstrings).